//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2024. 05. 05. 17:47:41
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace enNamespace
{
    public partial class Felhasznalo {

        public Felhasznalo()
        {
            OnCreated();
        }

        public int id { get; set; }

        public string Nev { get; set; }

        public string EMail { get; set; }

        public int szoba_id { get; set; }

        public string Szin { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
